{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "61725763-0114-46a6-82f5-437ad3b5e01b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-27 16:27:13.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.421 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-27 16:27:13.422 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-27 16:27:13.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-27 16:27:13.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "\n",
    "# 1. Configuración de la interfaz\n",
    "st.set_page_config(page_title=\"Inspector de Empalmes\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🔍 Consulta de Consumo por Instalación\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# 2. Función optimizada para cargar datos\n",
    "@st.cache_data\n",
    "def cargar_datos():\n",
    "    return pd.read_csv(\"datos.csv\")\n",
    "\n",
    "try:\n",
    "    df = cargar_datos()\n",
    "\n",
    "    # 3. Buscador lateral o principal\n",
    "    busqueda = st.text_input(\"Ingrese el número de Instalación (ID):\", placeholder=\"Ej: 123456\")\n",
    "\n",
    "    if busqueda:\n",
    "        # Filtrado riguroso convirtiendo a string\n",
    "        resultado = df[df['instalacion'].astype(str) == str(busqueda)]\n",
    "\n",
    "        if not resultado.empty:\n",
    "            # Mostrar información clave de forma destacada\n",
    "            medidor = resultado['numero de medidor'].values[0]\n",
    "            st.info(f\"**Medidor asociado:** {medidor}\")\n",
    "            \n",
    "            # 4. Procesamiento de los 64 meses\n",
    "            columnas_meses = [f\"mes_{i}\" for i in range(1, 65)]\n",
    "            \n",
    "            # Verificamos que las columnas existan antes de graficar\n",
    "            columnas_presentes = [c for c in columnas_meses if c in df.columns]\n",
    "            \n",
    "            if len(columnas_presentes) > 0:\n",
    "                valores = resultado[columnas_presentes].values.flatten()\n",
    "                \n",
    "                df_grafico = pd.DataFrame({\n",
    "                    \"Mes\": [m.replace('_', ' ').title() for m in columnas_presentes],\n",
    "                    \"Consumo (kWh)\": valores\n",
    "                })\n",
    "\n",
    "                # 5. Gráfico interactivo adaptable a móvil\n",
    "                fig = px.line(\n",
    "                    df_grafico, \n",
    "                    x=\"Mes\", \n",
    "                    y=\"Consumo (kWh)\", \n",
    "                    title=f\"Historial de Consumo - Instalación {busqueda}\",\n",
    "                    markers=True,\n",
    "                    template=\"plotly_white\"\n",
    "                )\n",
    "                \n",
    "                # Optimización de etiquetas para pantallas pequeñas\n",
    "                fig.update_xaxes(nticks=15, tickangle=45)\n",
    "                fig.update_layout(hovermode=\"x unified\")\n",
    "                \n",
    "                st.plotly_chart(fig, use_container_width=True)\n",
    "            \n",
    "            # 6. Tabla detallada opcional\n",
    "            with st.expander(\"Ver tabla de datos técnicos\"):\n",
    "                st.dataframe(resultado)\n",
    "                \n",
    "        else:\n",
    "            st.warning(\"⚠️ No se encontró la instalación. Por favor, verifique el número.\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    st.error(\"❌ Error: No se encontró el archivo 'datos.csv'. Asegúrate de que esté en la misma carpeta que este script.\")\n",
    "except Exception as e:\n",
    "    st.error(f\"⚠️ Ocurrió un error inesperado: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
